### ISSUE TITLE
MacroCompiler is broken

### ISSUE THREAD

**Issue by donggyukim** [ucb-bar/barstools#26] opened 2017-10-05 07:28 UTC
At last, it's broken. It's not working with BOOM. I don't know which commit breaks it because there are a ton of rebased commits. In #24, I pointed out the problems which are not addressed.

The working version originally in the PR is:
https://github.com/ucb-bar/barstools/tree/donggyu-tmp

As we can see the history is totally different. I can't accept these changes. This is not about credits. The commits I pushed are **bug fixes**. They are all about functionalities. My commits are valuable enough to be preserved because I was directly applying it to rocket and boom, but they are disregarded. In #24, I was treated as if I have no knowledge of software engineering.

I'll point out again what's wrong with #24.
1.  The disaster starts from splitting mdf out from this repo. Now it's not clear the bug is in this repo or the mdf repo. On the other hand, mdf makes it much harder to import macro compiler. This repo is supposed to be imported to other projects, but I'm not sure why this is not disregarded. Obviously, this is a totally careless decision.
2. There are dozens of commits not related to functional changes.  I can't blame the commit among more than 50 commits.
3. The history should never be rewritten **in the same branch**. If you want to do, you should create another branch.
4. Refactoring should be done once everything is functionally working. In this sense, it's also very unfortunate the history is gone.
5. What exactly do the tests do? They don't help find a bug.

I just gave it up. I don't think I'm going to use barstools for midas/strober. Good luck to find a bug.

**Comment by edwardcwang** [comment] 2017-10-05 07:38
I'm sorry to hear that it's not working. Do you have a sample testcase with which which I can try to reproduce?

We should have a discussion about this. I think there are several allegations which are distorted or untrue.

As for the tests "not helping to find a bug", I would respectfully disagree there. I spent months of my time writing these test suites to help detect regressions in the code and to better understand the code while it was being refactored. I took care to run the test suites before every major set of refactors to make sure nothing broke.

With regards to the bug fix you mention - we had a discussion about this. Yes, I acknowledge that I made a mistake in rebasing your commit, since I misunderstood your comments about the history. Nonetheless, I wrote a testcase addressing the specific bug you were trying to fix, and I showed that it works using the test suite, so therefore I feel that it is unfair for you to say that the test suites do nothing to help find bugs.

As for the rebase vs squash - in this case, how would that have made a difference? If we had squashed it, all we would know is that someone in the giant commit, something is broken.

**Comment by shunshou** [comment] 2017-10-05 10:03
I'm just going to butt in here, because I feel a strong need to do so (sorry!):

I think it's really good that you are taking the initiative to improve stuff, add tests, and make things more modular/reusable...

But in general: when anyone works on something that involves multiple people, it's exceedingly important that he/she always consider how his/her actions (or inactions? lol... but that's more just about feature requests not being taken seriously or bug fixes never getting merged, because somehow ideology takes precedence over bug fixes O_O) affect other people's flow/ability to make progress. 

There's always some slight chance that changes might cause some unrecoverable (or difficult to recover from) damage. It's not really anyone's fault, BUT it'd be courteous to think doubly hard about ways to protect people and their work from that outcome. People have their own deadlines, and it just sucks when they have to expend considerable time + effort to fix code that they had previously written/vetted (even if it was originally suboptimal just to get the job done on time) because someone else accidentally injected a bug (not saying that happened) while refactoring. Yes, longevity and good practices are great, but I agree **very strongly** with Donggyu's #4. Obviously, there's no perfect time to refactor when any more than 1 person is using the code, but I'd personally prioritize immediate user needs (causing a **user** to miss a deadline or expend significantly more effort beyond their job description to compensate is a big no-no when it comes to customer adoption--that's actually been a gripe of mine since I started working with Chisel, although it's been getting better...) over expediting efforts towards reusability (which is admittedly extremely nice to have and definitely the long-term goal). And from past experiences, the scariest kind of refactor (that really needs to be well-timed) involves splitting features that maybe weren't initially designed with as much modularity as one would've liked (again due to time crunch!) out to separate repos and having things not work after that. :(

Also, as someone who is admittedly a noob at software engineering (~0 formal training), I totally know what it feels like to be schooled (intentional or not) on best practices, and it just doesn't feel good. :( We're all (hopefully) trying our best here... 

Maybe the main takeaway is that everyone can work on better communication (and that involves both what we say to each other and what we imply by our actions/inactions 'cause sometimes words and actions might not imply the same thing...) and trying to understand where the other person is coming from (shout-out to Adam for being really good at that). That's when collaboration leads to beauuuuuutifulllll thingssss and not a feeling of being undervalued or having your work stepped on :D... 

Re: rebasing, I think we've both encountered enough situations where so-called best practices actually made things more difficult ;). Not a bad intention, but don't get too rebase-happy, unless you're a one-man team. 

Re: tests, eh, it's probably impossible to come up with exhaustive tests for a problem like this. In that sense, it's commendable that you tried a lot of things. I just think it's important to remember that even though one might think he/she hasn't changed someone else's base functionality (and maybe that other person doesn't immediately realize it either if it's subtle), one's grasp of their use case still might be different from theirs, so it's probably bad to claim with 100% certainty that "nothing broke." Lost in translation~~~

**Comment by edwardcwang** [comment] 2017-10-06 08:42
Update: Donggyu and I had a discussion yesterday to resolve some of the issues in this thread. In order to help troubleshoot the issue, I asked Donggyu for the conf file of the BOOM configuration as well as the SRAM libs and ran a regression test using git bisect, and discovered that the new parallel implementation had some incorrect accounting for multi-ported memories, for which a fix is attempted in #27.

**Comment by colinschmidt** [comment] 2017-10-06 15:15
Was the bug only exposed on 2 read-write ports? Or did it also show up with 1read+1write?

**Comment by edwardcwang** [comment] 2017-10-06 19:44
It showed up for 1read+1write as well. I added a test to show that this is now fixed.

**Comment by colinschmidt** [comment] 2017-10-06 19:47
Bummer. That was definitely one of the test cases I you would get when you tested the port on any of our tapeouts.

**Closed** 2017-10-07 01:04 UTC
